import { useEffect, useMemo, useRef, useState } from 'react';
import type { CSSProperties, ReactNode } from 'react';
import { Activity, ArrowUpRight, Bot, BrainCircuit, Check, ChevronRight, Command, FileCode2, FolderKanban, Gauge, GitBranch, Layers3, LayoutDashboard, Menu, MonitorCog, Network, PanelLeft, Plus, Search, Settings, ShieldCheck, Sparkles, Terminal, X, Zap, Palette, Mic, Send, SlidersHorizontal, Sun, Moon, Orbit, Volume2 } from 'lucide-react';
import { dashboardService } from './services';
import { useUIStore } from './store';
import type { DashboardSnapshot, NavKey } from './types';
import './styles.css';

type IconType = typeof Activity;
type NavItem = { key: NavKey; label: string; icon: IconType };
type ThemeName = 'midnight' | 'glass' | 'violet' | 'high-contrast';

const navGroups: { label: string; items: NavItem[] }[] = [
  { label: 'Workspace', items: [{ key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { key: 'chats', label: 'Chats', icon: Sparkles }, { key: 'projects', label: 'Projects', icon: FolderKanban }, { key: 'workspaces', label: 'Workspaces', icon: Layers3 }, { key: 'research', label: 'Research', icon: Search }] },
  { label: 'Intelligence', items: [{ key: 'knowledge', label: 'Knowledge', icon: BrainCircuit }, { key: 'memory', label: 'Memory', icon: BrainCircuit }, { key: 'files', label: 'Files', icon: FileCode2 }, { key: 'models', label: 'Models', icon: Layers3 }, { key: 'agents', label: 'Agents', icon: Bot }] },
  { label: 'Runtime', items: [{ key: 'boundary', label: 'Boundary', icon: ShieldCheck }, { key: 'sandbox', label: 'Sandbox', icon: Orbit }, { key: 'plugins', label: 'Plugins', icon: Network }, { key: 'automation', label: 'Automation', icon: GitBranch }] },
  { label: 'Observe', items: [{ key: 'tasks', label: 'Tasks', icon: Activity }, { key: 'logs', label: 'Logs', icon: Terminal }, { key: 'analytics', label: 'Analytics', icon: Gauge }, { key: 'monitoring', label: 'Monitoring', icon: MonitorCog }, { key: 'settings', label: 'Settings', icon: Settings }] },
];
const allNav = navGroups.flatMap((group) => group.items);

function App() {
  const { mode, activeNav, commandOpen, setMode, setActiveNav, setCommandOpen } = useUIStore();
  const [data, setData] = useState<DashboardSnapshot>();
  const [mobileNav, setMobileNav] = useState(false);
  const [theme, setTheme] = useState<ThemeName>('midnight');
  const [toast, setToast] = useState('');
  const [assistantOpen, setAssistantOpen] = useState(false);
  const [orbState, setOrbState] = useState<'listening' | 'working' | 'speaking'>('listening');

  useEffect(() => { dashboardService.getSnapshot().then(setData); const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); } if (event.key === 'Escape') setAssistantOpen(false); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [setCommandOpen]);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2600); return () => window.clearTimeout(timer); }, [toast]);
  const current = allNav.find((item) => item.key === activeNav) ?? allNav[0];
  const switchMode = () => { setMode(mode === 'static' ? 'alive' : 'static'); setToast(mode === 'static' ? 'Alive UI engaged' : 'Workspace UI engaged'); };

  if (mode === 'alive') return <AliveUI theme={theme} setTheme={setTheme} orbState={orbState} setOrbState={setOrbState} onSwitch={switchMode} open={assistantOpen} setOpen={setAssistantOpen} toast={toast} />;
  return <div className={`app theme-${theme}`}><aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><div className="brand-mark" /><div><div className="brand-name">ShadowByte</div><div className="brand-sub">AI runtime</div></div><button className="mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X /></button></div><nav>{navGroups.map((group) => <div key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(({ key, label, icon: Icon }) => <button className={`nav-item ${activeNav === key ? 'active' : ''}`} key={key} onClick={() => { setActiveNav(key); setMobileNav(false); }}><Icon /><span>{label}</span>{activeNav === key && <span className="nav-pulse" />}</button>)}</div>)}</nav><div className="nav-spacer" /><div className="side-foot"><div className="runtime"><i className="dot" /><span>Runtime online</span><span className="mono">v0.8.4</span></div></div></aside><main className="main"><header className="topbar"><button className="mobile-menu icon-button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div className="crumb"><PanelLeft /><span>Workspace /</span><strong>{current.label}</strong></div><div className="top-actions"><button className="mode-button" onClick={switchMode}><Orbit /><span>Assistant UI</span></button><button className="icon-button" onClick={() => setCommandOpen(true)} aria-label="Open command palette"><Command /></button><button className="icon-button notification" onClick={() => setToast('No new notifications')} aria-label="Notifications"><Activity /><i /></button></div></header><section className="content">{activeNav === 'dashboard' ? <Dashboard data={data} onAction={() => setAssistantOpen(true)} /> : <ModulePage nav={current} onAction={() => setAssistantOpen(true)} />}</section></main>{commandOpen && <CommandPalette close={() => setCommandOpen(false)} setActiveNav={setActiveNav} />}{assistantOpen && <AssistantDrawer close={() => setAssistantOpen(false)} setOrbState={setOrbState} />}{toast && <Toast message={toast} />}</div>;
}

function AliveUI({ theme, setTheme, orbState, setOrbState, onSwitch, open, setOpen, toast }: { theme: ThemeName; setTheme: (theme: ThemeName) => void; orbState: 'listening' | 'working' | 'speaking'; setOrbState: (state: 'listening' | 'working' | 'speaking') => void; onSwitch: () => void; open: boolean; setOpen: (open: boolean) => void; toast: string }) {
  const [prompt, setPrompt] = useState('');
  const [cards, setCards] = useState(['Runtime health is stable', '3 agents are waiting for intent']);
  const [progress, setProgress] = useState(72);
  const send = () => { if (!prompt.trim()) return; setOrbState('working'); setCards((current) => [`Working on “${prompt.trim()}”`, ...current].slice(0, 3)); setPrompt(''); setProgress(14); window.setTimeout(() => { setProgress(72); setOrbState('speaking'); }, 900); window.setTimeout(() => setOrbState('listening'), 1800); };
  return <div className={`alive-screen theme-${theme}`}><div className="alive-top"><div className="brand"><div className="brand-mark" /><div><div className="brand-name">ShadowByte</div><div className="brand-sub">Alive interface</div></div></div><div className="alive-actions"><button className="quiet-button" onClick={onSwitch}><PanelLeft /> Workspace UI</button><button className="quiet-button" onClick={() => setTheme(theme === 'midnight' ? 'glass' : 'midnight')}><Palette /> Theme</button></div></div><div className="alive-stage"><div className={`nerve-orb ${orbState}`}><div className="nerve-web">{Array.from({ length: 18 }, (_, index) => <i key={index} style={{ '--i': index } as CSSProperties} />)}</div><div className="orb-core"><span /><span /><span /></div></div><div className="orb-state"><span className="live-dot" />{orbState === 'working' ? 'Working through your request' : orbState === 'speaking' ? 'ShadowByte is speaking' : 'Listening for intent'}</div><div className="alive-cards">{cards.map((card, index) => <div className={`float-card card-${index}`} key={card}><div className="card-top"><Sparkles /><span>{index === 0 ? 'Live signal' : 'Assistant context'}</span></div><strong>{card}</strong><small>{index === 0 ? `${progress}% complete` : 'Ready when you are'}</small>{index === 0 && <div className="progress"><span style={{ width: `${progress}%` }} /></div>}</div>)}</div></div><div className="alive-composer"><button className="quiet-button"><Mic /></button><input value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing && event.keyCode !== 229) send(); }} placeholder="Tell ShadowByte what to do…" /><button className="send-button" onClick={send}><Send /></button></div>{open && <AssistantDrawer close={() => setOpen(false)} setOrbState={setOrbState} />}{toast && <Toast message={toast} />}</div>;
}

function Dashboard({ data, onAction }: { data?: DashboardSnapshot; onAction: () => void }) { return <><div className="page-heading"><div><div className="eyebrow">Workspace overview</div><h1>Good morning, operator.</h1><p>A calm surface for the intelligence running beneath it.</p></div><button className="quick" onClick={onAction}><Orbit /> Talk to Orb <kbd>⌘K</kbd></button></div><div className="overview-grid"><Stat label="Active agents" value={data?.activeAgents ?? '—'} hint="+2 online from last session" tone="cyan" /><Stat label="Tasks today" value={data?.tasksToday ?? '—'} hint="6 completed autonomously" tone="violet" /><Stat label="Memory indexed" value={data ? '1.2k' : '—'} hint="Across 4 workspaces" tone="green" /></div><div className="workspace-grid"><Panel title="Live activity" action="View timeline"><div className="activity">{data?.activity.map((item) => <div className="activity-row" key={item.id}><div className="activity-icon"><Sparkles /></div><div className="activity-copy">{item.title}<span>{item.detail}</span></div><span className="activity-time">now</span></div>) ?? <div className="loading-line">Loading workspace signals…</div>}</div></Panel><div className="glass orb-wrap"><div className="orb-ring ring-one" /><div className="orb-ring ring-two" /><div className="orb"><div className="orb-core" /></div><div className="orb-caption"><strong>ShadowByte ready</strong><span>{data?.runtime.uptime ?? 'Connecting to runtime'}</span></div><div className="orb-actions"><button onClick={onAction}><Zap /> Wake assistant</button></div></div><Panel title="Runtime health" action="Open monitor"><div className="health-list"><Health label="Inference gateway" value="Healthy" /><Health label="Memory index" value="Synced" /><Health label="Boundary policy" value="Enforced" /></div><div className="health-chart">{Array.from({ length: 9 }, (_, index) => <span key={index} style={{ height: `${28 + ((index * 17) % 55)}%` }} />)}</div></Panel></div><div className="lower-grid"><Panel title="Focus queue" action="Open tasks"><Queue icon={Bot} title="Review agent handoff" detail="Researcher → Planner" badge="Now" /><Queue icon={BrainCircuit} title="Index new memory" detail="12 documents waiting" badge="Next" /><Queue icon={ShieldCheck} title="Boundary review" detail="2 permission requests" badge="2" /></Panel><Panel title="Active workspaces" action="Manage"><Workspace name="ShadowByte core" meta="4 agents · 12 tasks" color="cyan" /><Workspace name="Research lab" meta="2 agents · 8 tasks" color="violet" /><Workspace name="Personal systems" meta="1 agent · quiet" color="green" /></Panel></div></> }
function Stat({ label, value, hint, tone }: { label: string; value: string | number; hint: string; tone: string }) { return <div className={`glass stat ${tone}`}><div className="eyebrow">{label}</div><div className="value">{value}</div><div className="hint">{hint}</div></div> }
function Panel({ title, action, children }: { title: string; action?: string; children: ReactNode }) { return <div className="glass panel"><div className="panel-head"><span className="panel-title">{title}</span>{action && <button className="link">{action} <ChevronRight /></button>}</div>{children}</div> }
function Health({ label, value }: { label: string; value: string }) { return <div className="health-row"><span><i className="dot" />{label}</span><strong>{value}<Check /></strong></div> }
function Queue({ icon: Icon, title, detail, badge }: { icon: IconType; title: string; detail: string; badge: string }) { return <div className="queue-row"><div className="queue-icon"><Icon /></div><div><strong>{title}</strong><span>{detail}</span></div><b>{badge}</b></div> }
function Workspace({ name, meta, color }: { name: string; meta: string; color: string }) { return <button className="workspace-row"><i className={`workspace-color ${color}`} /><span><strong>{name}</strong><small>{meta}</small></span><ChevronRight /></button> }

function ModulePage({ nav, onAction }: { nav: NavItem; onAction: () => void }) { const [query, setQuery] = useState(''); const rows = [{ title: `${nav.label} overview`, detail: 'Mock adapter connected', status: 'Ready' }, { title: 'Backend contract', detail: 'Awaiting integration', status: 'Placeholder' }, { title: 'Recent activity', detail: 'No new events', status: 'Quiet' }].filter((row) => row.title.toLowerCase().includes(query.toLowerCase())); return <><div className="page-heading"><div><div className="eyebrow">ShadowByte module</div><h1>{nav.label}</h1><p>Everything here is alive, inspectable, and ready for the runtime contract.</p></div><button className="quick" onClick={onAction}><Orbit /> Ask ShadowByte</button></div><div className="module-toolbar"><div className="search-field"><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${nav.label.toLowerCase()}…`} /></div><button className="toolbar-button"><Plus /> New</button><button className="toolbar-button subtle"><SlidersHorizontal /> Filter</button></div><div className="module-layout"><div className="glass module-table"><div className="table-head"><span>Name</span><span>Status</span><span /></div>{rows.map((row) => <div className="module-row" key={row.title}><div className="module-name"><div className="row-icon"><nav.icon /></div><span><strong>{row.title}</strong><small>{row.detail}</small></span></div><span className={`status-pill ${row.status.toLowerCase()}`}>{row.status}</span><ChevronRight /></div>)}</div><div className="glass side-insight"><div className="eyebrow">Runtime note</div><h3>Your surface is ready.</h3><p>Use the assistant switcher anytime to let ShadowByte arrange this view around your intent.</p><button className="text-button" onClick={onAction}>Open assistant <ChevronRight /></button></div></div></> }

function AssistantDrawer({ close, setOrbState }: { close: () => void; setOrbState: (state: 'listening' | 'working' | 'speaking') => void }) { const [message, setMessage] = useState(''); const inputRef = useRef<HTMLInputElement>(null); useEffect(() => inputRef.current?.focus(), []); return <div className="drawer-backdrop" onClick={close}><section className="assistant-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-head"><div><div className="eyebrow">ShadowByte assistant</div><h2>What should I surface?</h2></div><button className="icon-button" onClick={close} aria-label="Close assistant"><X /></button></div><div className="drawer-orb"><div className="mini-orb"><div /></div><span><i className="dot" /> Listening</span></div><div className="assistant-log"><div className="assistant-line"><Orbit /><span>I can open modules, summarize activity, start work, or change your interface.</span></div></div><div className="assistant-input"><input ref={inputRef} value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.nativeEvent.isComposing && event.keyCode !== 229) { setOrbState('working'); setMessage(''); window.setTimeout(() => setOrbState('speaking'), 800); } }} placeholder="Ask ShadowByte anything…" /><button className="send-button"><Send /></button></div><div className="suggestions"><button onClick={() => setMessage('Show me runtime health')}>Runtime health</button><button onClick={() => setMessage('Open recent tasks')}>Recent tasks</button><button onClick={() => setMessage('Change theme')}>Change theme</button></div></section></div> }
function Toast({ message }: { message: string }) { return <div className="toast"><Check />{message}</div> }
function CommandPalette({ close, setActiveNav }: { close: () => void; setActiveNav: (nav: NavKey) => void }) { const [query, setQuery] = useState(''); const commands = useMemo(() => allNav.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [query]); return <div className="palette-backdrop" onClick={close}><div className="palette glass" onClick={(event) => event.stopPropagation()}><div className="palette-input"><Search /><input value={query} autoFocus onChange={(event) => setQuery(event.target.value)} placeholder="Search commands, pages, memory…" /><kbd>ESC</kbd><button onClick={close} aria-label="Close"><X /></button></div><div className="palette-section">Navigate</div>{commands.map(({ label, icon: Icon, key }) => <button className="palette-row" key={key} onClick={() => { setActiveNav(key); close(); }}><Icon />{label}<span>↵</span></button>)}</div></div> }
export default App;
