import { useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { Activity, Bot, Box, BrainCircuit, Check, ChevronRight, Command, FileCode2, FolderKanban, Gauge, GitBranch, Layers3, LayoutDashboard, Menu, MonitorCog, Network, PanelLeft, Plus, Search, Settings, ShieldCheck, Sparkles, Terminal, X, Zap } from 'lucide-react';
import { dashboardService } from './services';
import { useUIStore } from './store';
import type { DashboardSnapshot, NavKey } from './types';
import './styles.css';

type IconType = typeof Activity;
type NavItem = { key: NavKey; label: string; icon: IconType };

const navGroups: { label: string; items: NavItem[] }[] = [
  { label: 'Workspace', items: [{ key: 'dashboard', label: 'Dashboard', icon: LayoutDashboard }, { key: 'chats', label: 'Chats', icon: Sparkles }, { key: 'projects', label: 'Projects', icon: FolderKanban }, { key: 'workspaces', label: 'Workspaces', icon: Layers3 }, { key: 'research', label: 'Research', icon: Search }] },
  { label: 'Intelligence', items: [{ key: 'knowledge', label: 'Knowledge', icon: BrainCircuit }, { key: 'memory', label: 'Memory', icon: BrainCircuit }, { key: 'files', label: 'Files', icon: FileCode2 }, { key: 'models', label: 'Models', icon: Layers3 }, { key: 'agents', label: 'Agents', icon: Bot }] },
  { label: 'Runtime', items: [{ key: 'boundary', label: 'Boundary', icon: ShieldCheck }, { key: 'sandbox', label: 'Sandbox', icon: Box }, { key: 'plugins', label: 'Plugins', icon: Network }, { key: 'automation', label: 'Automation', icon: GitBranch }] },
  { label: 'Observe', items: [{ key: 'tasks', label: 'Tasks', icon: Activity }, { key: 'logs', label: 'Logs', icon: Terminal }, { key: 'analytics', label: 'Analytics', icon: Gauge }, { key: 'monitoring', label: 'Monitoring', icon: MonitorCog }, { key: 'settings', label: 'Settings', icon: Settings }] },
];
const allNav = navGroups.flatMap((group) => group.items);

function App() {
  const { mode, activeNav, commandOpen, setMode, setActiveNav, setCommandOpen } = useUIStore();
  const [data, setData] = useState<DashboardSnapshot>();
  const [mobileNav, setMobileNav] = useState(false);
  useEffect(() => { dashboardService.getSnapshot().then(setData); const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setCommandOpen(true); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [setCommandOpen]);
  const current = allNav.find((item) => item.key === activeNav) ?? allNav[0];
  return <div className={`app ${mode === 'alive' ? 'alive-mode' : ''}`}>
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><div className="brand-mark" /><div><div className="brand-name">ShadowByte</div><div className="brand-sub">AI runtime</div></div><button className="mobile-close" onClick={() => setMobileNav(false)} aria-label="Close navigation"><X /></button></div><nav>{navGroups.map((group) => <div key={group.label}><div className="nav-label">{group.label}</div>{group.items.map(({ key, label, icon: Icon }) => <button className={`nav-item ${activeNav === key ? 'active' : ''}`} key={key} onClick={() => { setActiveNav(key); setMobileNav(false); }}><Icon /><span>{label}</span>{activeNav === key && <span className="nav-pulse" />}</button>)}</div>)}</nav><div className="nav-spacer" /><div className="side-foot"><div className="runtime"><i className="dot" /><span>Runtime online</span><span className="mono">v0.8.4</span></div></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu icon-button" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div className="crumb"><PanelLeft /><span>Workspace /</span><strong>{current.label}</strong></div><div className="top-actions"><button className="mode-button" onClick={() => setMode(mode === 'static' ? 'alive' : 'static')}><Sparkles /><span>{mode === 'static' ? 'Static UI' : 'Alive UI'}</span></button><button className="icon-button" onClick={() => setCommandOpen(true)} aria-label="Open command palette"><Command /></button><button className="icon-button notification" aria-label="Notifications"><Activity /><i /></button></div></header><section className="content">{activeNav === 'dashboard' ? <Dashboard data={data} mode={mode} onAction={() => setCommandOpen(true)} /> : <ModulePage nav={current} mode={mode} onAction={() => setCommandOpen(true)} />}</section></main>{commandOpen && <CommandPalette close={() => setCommandOpen(false)} setActiveNav={setActiveNav} />}</div>;
}

function Dashboard({ data, mode, onAction }: { data?: DashboardSnapshot; mode: string; onAction: () => void }) {
  return <><div className="page-heading"><div><div className="eyebrow">{mode === 'alive' ? 'Living workspace' : 'Workspace overview'}</div><h1>Good morning, operator.</h1><p>{mode === 'alive' ? 'Your runtime is listening. I surfaced what needs your attention.' : 'A calm surface for the intelligence running beneath it.'}</p></div><button className="quick" onClick={onAction}><Command /> Quick actions <kbd>⌘K</kbd></button></div><div className="overview-grid"><Stat label="Active agents" value={data?.activeAgents ?? '—'} hint="+2 online from last session" tone="cyan" /><Stat label="Tasks today" value={data?.tasksToday ?? '—'} hint="6 completed autonomously" tone="violet" /><Stat label="Memory indexed" value={data ? '1.2k' : '—'} hint="Across 4 workspaces" tone="green" /></div><div className="workspace-grid"><Panel title="Live activity" action="View timeline"><div className="activity">{data?.activity.map((item) => <div className="activity-row" key={item.id}><div className="activity-icon"><Sparkles /></div><div className="activity-copy">{item.title}<span>{item.detail}</span></div><span className="activity-time">now</span></div>) ?? <div className="loading-line">Loading workspace signals…</div>}</div></Panel><div className="glass orb-wrap"><div className="orb-ring ring-one" /><div className="orb-ring ring-two" /><div className="orb"><div className="orb-core" /></div><div className="orb-caption"><strong>{mode === 'alive' ? 'Listening for intent' : 'ShadowByte ready'}</strong><span>{data?.runtime.uptime ?? 'Connecting to runtime'}</span></div><div className="orb-actions"><button onClick={onAction}><Zap /> Wake assistant</button></div></div><Panel title="Runtime health" action="Open monitor"><div className="health-list"><Health label="Inference gateway" value="Healthy" /><Health label="Memory index" value="Synced" /><Health label="Boundary policy" value="Enforced" /></div><div className="health-chart"><span /><span /><span /><span /><span /><span /><span /><span /><span /><span /><span /><span /></div></Panel></div><div className="lower-grid"><Panel title="Focus queue"><Queue icon={Bot} title="Review agent permissions" detail="Boundary · 4 min ago" badge="Review" /><Queue icon={BrainCircuit} title="Index product research" detail="Research · queued" badge="Queued" /><Queue icon={Terminal} title="Clean sandbox artifacts" detail="Sandbox · tomorrow" badge="Scheduled" /></Panel><Panel title="Active workspaces" action="Manage"><div className="workspace-list"><Workspace name="Command Center" meta="3 agents · 12 tasks" color="cyan" /><Workspace name="Product research" meta="2 agents · 8 sources" color="violet" /><Workspace name="Quiet notes" meta="Personal · synced" color="green" /></div></Panel></div></>;
}
function Stat({ label, value, hint, tone }: { label: string; value: string | number; hint: string; tone: string }) { return <div className={`glass stat ${tone}`}><div className="eyebrow">{label}</div><div className="value">{value}</div><div className="hint">{hint}</div></div>; }
function Panel({ title, action, children }: { title: string; action?: string; children: ReactNode }) { return <div className="glass panel"><div className="panel-head"><span className="panel-title">{title}</span>{action && <button className="link">{action} <ChevronRight /></button>}</div>{children}</div>; }
function Health({ label, value }: { label: string; value: string }) { return <div className="health-row"><span><i className="dot" />{label}</span><strong>{value}<Check /></strong></div>; }
function Queue({ icon: Icon, title, detail, badge }: { icon: IconType; title: string; detail: string; badge: string }) { return <div className="queue-row"><div className="queue-icon"><Icon /></div><div><strong>{title}</strong><span>{detail}</span></div><b>{badge}</b></div>; }
function Workspace({ name, meta, color }: { name: string; meta: string; color: string }) { return <button className="workspace-row"><i className={`workspace-color ${color}`} /><span><strong>{name}</strong><small>{meta}</small></span><ChevronRight /></button>; }

function ModulePage({ nav, mode, onAction }: { nav: NavItem; mode: string; onAction: () => void }) {
  const configs: Record<string, { eyebrow: string; description: string; rows: { title: string; detail: string; status: string }[] }> = {
    chats: { eyebrow: 'Conversation workspace', description: 'Branches, context, and model output in one focused surface.', rows: [{ title: 'Planning the next release', detail: 'GPT-5 · 18 messages', status: 'Active' }, { title: 'Research synthesis', detail: 'Claude Sonnet · 42 messages', status: 'Pinned' }, { title: 'Untitled conversation', detail: 'Local model · draft', status: 'Draft' }] },
    projects: { eyebrow: 'Project control', description: 'Organize runtime work into durable, focused environments.', rows: [{ title: 'ShadowByte core', detail: '12 tasks · 4 agents', status: 'Active' }, { title: 'Knowledge layer', detail: '8 tasks · 2 agents', status: 'Planning' }, { title: 'Personal systems', detail: '3 tasks · 1 agent', status: 'Quiet' }] },
    agents: { eyebrow: 'Agent control', description: 'See what your runtime is doing and shape its boundaries.', rows: [{ title: 'Researcher', detail: 'Browsing · 2 tools', status: 'Running' }, { title: 'Planner', detail: 'Waiting for input', status: 'Idle' }, { title: 'Archivist', detail: 'Memory indexing', status: 'Running' }] },
    boundary: { eyebrow: 'Runtime boundary', description: 'Permission-aware controls for everything the runtime can touch.', rows: [{ title: 'Filesystem', detail: 'Workspace scope only', status: 'Enforced' }, { title: 'Network', detail: 'Approved domains', status: 'Enforced' }, { title: 'Processes', detail: 'User confirmation', status: 'Review' }] },
    settings: { eyebrow: 'Control center', description: 'Tune ShadowByte to your exact working style.', rows: [{ title: 'Appearance', detail: 'Theme, glass, typography', status: 'Configure' }, { title: 'Workspace', detail: 'Layouts, panels, shortcuts', status: 'Configure' }, { title: 'Accessibility', detail: 'Motion, contrast, input', status: 'Configure' }] },
  };
  const config = configs[nav.key] ?? { eyebrow: 'ShadowByte module', description: mode === 'alive' ? 'The living interface will arrange this surface around your intent.' : 'This module is ready for its backend contract.', rows: [{ title: `${nav.label} overview`, detail: 'Mock adapter connected', status: 'Ready' }, { title: 'Backend contract', detail: 'Awaiting integration', status: 'Placeholder' }, { title: 'Recent activity', detail: 'No new events', status: 'Quiet' }] };
  return <><div className="page-heading"><div><div className="eyebrow">{config.eyebrow}</div><h1>{nav.label}</h1><p>{config.description}</p></div><button className="quick" onClick={onAction}><Sparkles /> Ask ShadowByte</button></div><div className="module-toolbar"><div className="search-field"><Search /><input placeholder={`Search ${nav.label.toLowerCase()}…`} /></div><button className="toolbar-button"><Plus /> New</button><button className="toolbar-button subtle">Filter</button></div><div className="module-layout"><div className="glass module-table"><div className="table-head"><span>Name</span><span>Status</span><span /></div>{config.rows.map((row) => <div className="module-row" key={row.title}><div className="module-name"><div className="row-icon"><nav.icon /></div><span><strong>{row.title}</strong><small>{row.detail}</small></span></div><span className={`status-pill ${row.status.toLowerCase()}`}>{row.status}</span><ChevronRight /></div>)}</div><div className="glass side-insight"><div className="eyebrow">Runtime note</div><h3>{mode === 'alive' ? 'I can shape this view.' : 'A clean surface for later.'}</h3><p>{mode === 'alive' ? 'Switching to Alive UI lets the assistant prioritize the cards and signals that matter most right now.' : 'This page is connected to a typed mock adapter. Replace the adapter when the backend contract is ready.'}</p><button className="text-button" onClick={onAction}>Open command palette <ChevronRight /></button></div></div></>;
}
function CommandPalette({ close, setActiveNav }: { close: () => void; setActiveNav: (nav: NavKey) => void }) { const [query, setQuery] = useState(''); const commands = useMemo(() => allNav.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [query]); return <div className="palette-backdrop" onClick={close}><div className="palette glass" onClick={(event) => event.stopPropagation()}><div className="palette-input"><Search /><input value={query} autoFocus onChange={(event) => setQuery(event.target.value)} placeholder="Search commands, pages, memory…" /><kbd>ESC</kbd><button onClick={close} aria-label="Close"><X /></button></div><div className="palette-section">Navigate</div>{commands.map(({ label, icon: Icon, key }) => <button className="palette-row" key={key} onClick={() => { setActiveNav(key); close(); }}><Icon />{label}<span>↵</span></button>)}</div></div>; }
export default App;
