export type PageKind = 'overview' | 'conversation' | 'collection' | 'monitoring' | 'editor' | 'settings' | 'graph' | 'terminal' | 'catalog'

export type PageDefinition = {
  key: string
  kind: PageKind
  eyebrow: string
  title: string
  description: string
  primaryAction: string
  metrics: string[]
  sections: { title: string; detail: string; accent: 'cyan' | 'violet' | 'amber' | 'green' }[]
  backend: string[]
}

const page = (key: string, kind: PageKind, eyebrow: string, title: string, description: string, primaryAction: string, metrics: string[], sections: PageDefinition['sections'], backend: string[]): PageDefinition => ({ key, kind, eyebrow, title, description, primaryAction, metrics, sections, backend })

export const pageRegistry: Record<string, PageDefinition> = {
  dashboard: page('dashboard', 'overview', 'Runtime cockpit', 'Dashboard', 'A live read of what ShadowByte is doing, what needs attention, and where the runtime is headed next.', 'Open assistant', ['3 active agents', '84% memory', '12 tasks today'], [{ title: 'Focus queue', detail: 'Prioritized work with next actions and owners.', accent: 'cyan' }, { title: 'Runtime pulse', detail: 'Model, memory, boundary, and task health in one view.', accent: 'violet' }, { title: 'Workspace weather', detail: 'Recent projects, branches, and attention signals.', accent: 'green' }], ['/api/status', '/api/tasks', '/ws/status']),
  chats: page('chats', 'conversation', 'Conversation control', 'Chats', 'Branch conversations, inspect context, and keep assistant work in motion.', 'New chat', ['12 open threads', '4 pinned', '2 streaming'], [{ title: 'Thread navigator', detail: 'Search, pin, branch, archive, and restore conversations.', accent: 'cyan' }, { title: 'Context rail', detail: 'Files, memories, tools, and model settings attached to a thread.', accent: 'violet' }, { title: 'Live transcript', detail: 'Streaming messages with retry, share, speak, and copy actions.', accent: 'green' }], ['/api/chats', '/api/chats/:id/messages', '/ws/chat']),
  projects: page('projects', 'collection', 'Build surfaces', 'Projects', 'Projects group runtime intent, files, agents, and deployable work.', 'Create project', ['8 projects', '24 branches', '6 running'], [{ title: 'Project atlas', detail: 'A visual map of project health, branches, and runtime owners.', accent: 'cyan' }, { title: 'Recent work', detail: 'Files, commits, tasks, and agent actions grouped by project.', accent: 'violet' }, { title: 'Project controls', detail: 'Archive, duplicate, export, and assign workspace permissions.', accent: 'amber' }], ['/api/projects', '/api/projects/:id', '/ws/projects']),
  workspaces: page('workspaces', 'collection', 'Workspace orchestration', 'Workspaces', 'Save layouts, tools, context, and page state as repeatable operating environments.', 'New workspace', ['5 saved layouts', '2 shared', '1 active'], [{ title: 'Layout gallery', detail: 'Focus, developer, research, automation, monitoring, and custom presets.', accent: 'cyan' }, { title: 'Workspace snapshots', detail: 'Restore pages, tabs, selections, and assistant context together.', accent: 'violet' }, { title: 'Shared workspaces', detail: 'Permission-aware collaboration and exported workspace recipes.', accent: 'green' }], ['/api/workspaces', '/api/workspaces/:id/snapshots', '/ws/workspaces']),
  research: page('research', 'collection', 'Evidence workspace', 'Research', 'Collect sources, compare claims, and turn research into durable memory.', 'Start research', ['18 sources', '6 claims', '3 syntheses'], [{ title: 'Source board', detail: 'Citations, trust signals, notes, and source snapshots.', accent: 'cyan' }, { title: 'Claim graph', detail: 'Evidence relationships and contradictions displayed spatially.', accent: 'violet' }, { title: 'Synthesis queue', detail: 'Turn evidence into briefs, tasks, and memory entries.', accent: 'amber' }], ['/api/research', '/api/search', '/ws/research']),
  knowledge: page('knowledge', 'graph', 'Long-term context', 'Knowledge', 'Explore what ShadowByte remembers, how concepts connect, and where confidence is weak.', 'Add knowledge', ['1,248 nodes', '94 clusters', '7 weak links'], [{ title: 'Knowledge graph', detail: 'Browse concepts, sources, and relationships by workspace.', accent: 'cyan' }, { title: 'Confidence lanes', detail: 'Surface stale, conflicting, and low-confidence memories.', accent: 'amber' }, { title: 'Recall tester', detail: 'Search memory with citations and relevance explanations.', accent: 'violet' }], ['/api/knowledge/search', '/api/memory', '/ws/memory']),
  memory: page('memory', 'collection', 'Context layer', 'Memory', 'Manage durable context, retention, and the boundaries of what the assistant should recall.', 'Capture memory', ['642 durable', '38 recent', '92% recall'], [{ title: 'Memory inbox', detail: 'Review, edit, merge, expire, or promote candidate memories.', accent: 'cyan' }, { title: 'Retention policy', detail: 'Control workspace, project, conversation, and private context.', accent: 'violet' }, { title: 'Recall audit', detail: 'See why a memory surfaced and remove it from future context.', accent: 'amber' }], ['/api/memory', '/api/memory/:id', '/ws/memory']),
  files: page('files', 'editor', 'Artifact layer', 'Files', 'Browse, preview, annotate, and attach workspace artifacts without losing context.', 'Upload file', ['2,406 files', '18.4 GB', '12 recent'], [{ title: 'File explorer', detail: 'List, grid, filters, favorites, tags, and recent activity.', accent: 'cyan' }, { title: 'Preview stage', detail: 'Markdown, code, media, PDF, and structured data previews.', accent: 'violet' }, { title: 'Attachment dock', detail: 'Attach artifacts to chats, research, agents, and tasks.', accent: 'green' }], ['/api/files', '/api/files/:id/preview', '/ws/files']),
  models: page('models', 'catalog', 'Inference control', 'Models', 'Load models, inspect capacity, and choose the right response profile.', 'Add model', ['4 available', '2 loaded', '28 GB free'], [{ title: 'Model shelf', detail: 'Compare capability, context, speed, cost, and local availability.', accent: 'cyan' }, { title: 'Load monitor', detail: 'Track warm, cold, loading, and unloading model states.', accent: 'amber' }, { title: 'Routing policy', detail: 'Choose how Fast, Chat, Code, and Write modes select models.', accent: 'violet' }], ['/api/models', '/api/models/:id/load', '/ws/models']),
  agents: page('agents', 'collection', 'Runtime operators', 'Agents', 'Compose agents, assign tools, and monitor their current intent.', 'Create agent', ['6 agents', '3 running', '11 tools'], [{ title: 'Agent roster', detail: 'Identity, role, tools, model, memory, and current state.', accent: 'cyan' }, { title: 'Run timeline', detail: 'Steps, tool calls, retries, approvals, and outputs.', accent: 'violet' }, { title: 'Capability matrix', detail: 'Permission-aware access to files, network, sandbox, and memory.', accent: 'amber' }], ['/api/agents', '/api/agents/:id/runs', '/ws/agents']),
  boundary: page('boundary', 'monitoring', 'Safety perimeter', 'Boundary', 'Inspect permissions, approvals, policy checks, and runtime guardrails.', 'Run scan', ['18 policies', '0 violations', '3 approvals'], [{ title: 'Policy matrix', detail: 'Network, filesystem, process, privacy, and tool boundaries.', accent: 'cyan' }, { title: 'Approval queue', detail: 'Review sensitive actions before agents execute them.', accent: 'amber' }, { title: 'Audit timeline', detail: 'Trace who requested, approved, denied, or retried an action.', accent: 'violet' }], ['/api/boundary/policies', '/api/boundary/scans', '/ws/boundary']),
  sandbox: page('sandbox', 'terminal', 'Execution chamber', 'Sandbox', 'Run isolated commands and inspect execution artifacts without exposing the host.', 'New session', ['2 sessions', '14 commands', '0 failures'], [{ title: 'Session deck', detail: 'Isolated workspaces, resource limits, and lifecycle controls.', accent: 'cyan' }, { title: 'Command stream', detail: 'Live stdout, stderr, exit codes, and cancellation controls.', accent: 'green' }, { title: 'Artifact shelf', detail: 'Outputs, logs, patches, and downloadable results.', accent: 'violet' }], ['/api/sandbox/sessions', '/api/terminal/commands', '/ws/tasks']),
  plugins: page('plugins', 'catalog', 'Extension layer', 'Plugins', 'Install and manage modules that extend pages, tools, commands, themes, and cards.', 'Browse marketplace', ['18 installed', '4 updates', '2 disabled'], [{ title: 'Extension catalog', detail: 'Capabilities, permissions, versions, and compatibility.', accent: 'cyan' }, { title: 'Plugin surfaces', detail: 'Pages, widgets, commands, settings, and context actions.', accent: 'violet' }, { title: 'Permission review', detail: 'Approve or revoke plugin access before activation.', accent: 'amber' }], ['/api/plugins', '/api/plugins/:id/install', '/ws/system']),
  marketplace: page('marketplace', 'catalog', 'Capability exchange', 'Marketplace', 'Discover tools, agents, models, themes, and workspace recipes.', 'Explore catalog', ['124 listings', '18 verified', '6 new'], [{ title: 'Curated capabilities', detail: 'Verified agents, models, tools, plugins, and layouts.', accent: 'cyan' }, { title: 'Trust ledger', detail: 'Publisher identity, permissions, reviews, and update history.', accent: 'amber' }, { title: 'Install queue', detail: 'Stage, approve, install, and rollback extensions.', accent: 'violet' }], ['/api/marketplace', '/api/marketplace/:id/install']),
  automation: page('automation', 'collection', 'Orchestration', 'Automation', 'Build repeatable workflows from triggers, schedules, agents, and approvals.', 'Create automation', ['12 automations', '4 scheduled', '96% success'], [{ title: 'Flow builder', detail: 'Compose steps with retry, branching, approval, and timeout rules.', accent: 'cyan' }, { title: 'Schedule board', detail: 'Review upcoming runs and conflicts across workspaces.', accent: 'violet' }, { title: 'Run history', detail: 'Inspect outputs, failures, retries, and saved artifacts.', accent: 'amber' }], ['/api/automation', '/api/automation/:id/runs', '/ws/tasks']),
  tasks: page('tasks', 'monitoring', 'Work queue', 'Tasks', 'Track everything the runtime, agents, and you have asked ShadowByte to do.', 'Create task', ['12 today', '4 running', '2 blocked'], [{ title: 'Priority queue', detail: 'Sort by urgency, owner, project, and dependency.', accent: 'cyan' }, { title: 'Execution lanes', detail: 'See waiting, running, blocked, retrying, and completed work.', accent: 'violet' }, { title: 'Task handoff', detail: 'Move work between agents, people, automations, and schedules.', accent: 'green' }], ['/api/tasks', '/api/tasks/:id', '/ws/tasks']),
  history: page('history', 'collection', 'Trace archive', 'History', 'Review the sequence of changes, assistant runs, workspace transitions, and decisions.', 'Filter history', ['2,804 events', '7 days', '18 actors'], [{ title: 'Event timeline', detail: 'Chronological activity with filters and expandable payloads.', accent: 'cyan' }, { title: 'Decision trail', detail: 'Why a model, tool, memory, or policy path was selected.', accent: 'violet' }, { title: 'Restore points', detail: 'Return to prior workspace and conversation states.', accent: 'amber' }], ['/api/history', '/api/history/:id']),
  logs: page('logs', 'terminal', 'System observability', 'Logs', 'Search structured runtime logs, events, errors, and trace identifiers.', 'Live tail', ['18k events', '0 critical', '42 traces'], [{ title: 'Structured stream', detail: 'Filter by service, severity, request, actor, and trace.', accent: 'cyan' }, { title: 'Error clusters', detail: 'Group recurring failures and attach remediation notes.', accent: 'amber' }, { title: 'Trace explorer', detail: 'Follow an action from UI intent to backend response.', accent: 'violet' }], ['/api/logs', '/api/logs/stream', '/ws/logs']),
  analytics: page('analytics', 'monitoring', 'Runtime intelligence', 'Analytics', 'Understand usage, latency, model performance, costs, and workspace throughput.', 'Create report', ['98.4% uptime', '1.8s p95', '642 runs'], [{ title: 'Performance atlas', detail: 'Latency, throughput, errors, and model utilization over time.', accent: 'cyan' }, { title: 'Usage economics', detail: 'Token, compute, storage, and tool usage by workspace.', accent: 'amber' }, { title: 'Outcome signals', detail: 'Task completion, retries, handoffs, and user feedback.', accent: 'violet' }], ['/api/analytics', '/api/analytics/reports']),
  monitoring: page('monitoring', 'monitoring', 'Runtime health', 'Monitoring', 'Watch service health, resource pressure, queue depth, and live incidents.', 'Open monitor', ['12 services', '99.9% healthy', '0 incidents'], [{ title: 'Service map', detail: 'Gateway, agents, memory, models, storage, and integrations.', accent: 'cyan' }, { title: 'Resource pressure', detail: 'CPU, memory, GPU, disk, network, and queue pressure.', accent: 'amber' }, { title: 'Incident desk', detail: 'Acknowledge, assign, silence, and resolve runtime incidents.', accent: 'violet' }], ['/api/monitoring', '/api/monitoring/incidents', '/ws/monitoring']),
  notifications: page('notifications', 'collection', 'Attention layer', 'Notifications', 'Keep important runtime changes visible without interrupting the workspace.', 'Mark all read', ['8 unread', '3 urgent', '24 today'], [{ title: 'Priority inbox', detail: 'Group by urgency, workspace, agent, and event type.', accent: 'cyan' }, { title: 'Delivery rules', detail: 'Choose toast, banner, sound, email, or silent delivery.', accent: 'violet' }, { title: 'Event subscriptions', detail: 'Subscribe to agent, task, model, boundary, and system signals.', accent: 'green' }], ['/api/notifications', '/ws/notifications']),
  security: page('security', 'settings', 'Trust center', 'Security', 'Review sessions, credentials, permissions, audit records, and privacy boundaries.', 'Review security', ['2 sessions', '0 alerts', '18 policies'], [{ title: 'Session control', detail: 'Active sessions, devices, sign-out, and trusted origins.', accent: 'cyan' }, { title: 'Credential vault', detail: 'Connectors, secrets, scopes, rotation, and last use.', accent: 'amber' }, { title: 'Privacy ledger', detail: 'Data retention, exports, deletion, and access history.', accent: 'violet' }], ['/api/security/sessions', '/api/security/credentials', '/api/security/audit']),
  developer: page('developer', 'terminal', 'Build surface', 'Developer', 'Inspect contracts, events, API calls, extension points, and runtime diagnostics.', 'Open API explorer', ['42 routes', '18 events', '6 SDKs'], [{ title: 'API explorer', detail: 'Request/response schemas, auth, errors, and examples.', accent: 'cyan' }, { title: 'Event inspector', detail: 'Subscribe to internal events and replay payloads safely.', accent: 'violet' }, { title: 'Extension lab', detail: 'Prototype widgets, commands, themes, and service adapters.', accent: 'green' }], ['/api/routes', '/api/developer/events', '/ws/system']),
  settings: page('settings', 'settings', 'Control plane', 'Settings', 'Tune the Living Glass system, runtime preferences, accessibility, and workspace defaults.', 'Open theme studio', ['26 controls', '4 themes', '1 custom'], [{ title: 'Appearance studio', detail: 'Accent, blur, glass, density, typography, and motion.', accent: 'cyan' }, { title: 'Runtime defaults', detail: 'Model routing, memory, agent, sandbox, and network policy.', accent: 'violet' }, { title: 'Accessibility', detail: 'Keyboard, contrast, reduced motion, speech, and touch.', accent: 'green' }], ['/api/settings', '/api/settings/preferences']),
  help: page('help', 'collection', 'Support surface', 'Help', 'Find answers, inspect diagnostics, and send feedback without leaving ShadowByte.', 'Search help', ['48 articles', '2 diagnostics', '0 open tickets'], [{ title: 'Guided help', detail: 'Context-aware documentation for the page and action you are using.', accent: 'cyan' }, { title: 'Diagnostics', detail: 'Export a redacted support bundle with runtime health and traces.', accent: 'amber' }, { title: 'Feedback loop', detail: 'Share what worked, what broke, and what should improve.', accent: 'violet' }], ['/api/help/search', '/api/feedback'])
}

export const getPageDefinition = (key: string): PageDefinition => pageRegistry[key] ?? pageRegistry.dashboard

export const pageList = Object.values(pageRegistry)
